services:

    Polidog\TwigPathCheckerBundle\Finder\TemplateFinder:
        autowire: true

    Polidog\TwigPathCheckerBundle\Controller\ControllerResolver:
        autowire: true

    Polidog\TwigPathCheckerBundle\Command\CheckerCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'lint:twig:path' }

