services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Polidog\TwigPathCheckerBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection, Resources, TwigPathCheckerBundle.php}'
