services:

    Polidog\TwigPathCheckerBundle\Finder\TemplateFinder:
        autowire: true

    Polidog\TwigPathCheckerBundle\Controller\ControllerResolver:
        autowire: true

    Polidog\TwigPathCheckerBundle\Command\CheckerCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'lint:twig:path' }


    Polidog\TwigPathCheckerBundle\Route\Router:
        autowire: true

    Polidog\TwigPathCheckerBundle\Controller\ControllerCreator:
        autowire: true

    Polidog\TwigPathCheckerBundle\Template\AnnotationParser:
        autowire: true
