<?php

namespace Polidog\TwigPathCheckerBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class PolidogTwigPathCheckerBundle extends Bundle
{
    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }

}

